### ISSUE TITLE
Create basic prototype

### ISSUE THREAD

**Issue by dhcgn** [haevg-rz/Planungsboard#16]
Create a protoyp with basic feature

- [x] Dynamic grid for teams
- [x] Display cards
- [x] Ability to indicate a card which has a start and end in different quarters
- [x] Display cards with are assigned to only one quarter separately
- [x] Scroll through Quarters
- [x] Create a UserControl for each card which contains only two information: Name and effort

Actual simplified board:

![image](https://user-images.githubusercontent.com/6566207/76990845-e6dc9900-6948-11ea-9cd3-b70e779f6ee3.png)

**Comment by dhcgn** [comment]
@MarkusThiet please give a feedback

**Comment by MarkusThiet** [comment]
looks good

**Comment by dhcgn** [comment]
First result

![image](https://user-images.githubusercontent.com/6566207/77114722-4e6c1480-6a2d-11ea-85ec-5d4330e17ed0.png)

Drawback: Amount of quarters is for now fix

**Comment by dhcgn** [comment]
Gettings closer

![image](https://user-images.githubusercontent.com/6566207/77229234-ec2a2580-6b8c-11ea-88bd-91f322ee9c91.png)

**Comment by dhcgn** [comment]
Release current state https://github.com/haevg-rz/Planungsboard/releases/tag/v0.0.10

**Comment by dhcgn** [comment]
- Fix filter
- more test data
- add unit test

![image](https://user-images.githubusercontent.com/6566207/77238356-86ab5880-6bcf-11ea-8471-f88806747338.png)
