### ISSUE TITLE
Create new Quarter

### ISSUE THREAD

**Issue by MarkusThiet** [haevg-rz/Planungsboard#21]
de. Anlegen eines neuen Quartals

- [ ] For each existing Team a new empty "Quarter"column will be created
- [ ] Initialize: If no team is existing the first team will be created as well

**Comment by MarkusThiet** [comment]
For each existing Team a new empty "Quarter"column will be created

**Comment by MarkusThiet** [comment]
Initialize: If no team is existing the first team will be created as well

**Comment by dhcgn** [comment]
It is not possible to create a new quarter, but you can scroll from Q1-0000 to Q4-9999.
A Quarter is only relevant in cards, which can have assigned quarters.
